### ISSUE TITLE
requirements 오류

### ISSUE THREAD

**Issue by parkjihwanjay** [RyanKor/HTH#5]
backend_prepare branch를 clone하고 pipenv install -r requirements.txt를 했는데 unexpected syntax라고 뜨면서 설치가 안되네요 ㅜ

**Comment by parkjihwanjay** [comment]
> backend_prepare branch를 clone하고 pipenv install -r requirements.txt를 했는데 unexpected syntax라고 뜨면서 설치가 안되네요 ㅜ

-> 해결했습니다!

**Comment by RyanKor** [comment]
지환아!! 그건 pip install -r requirements.txt로 해야돼!! pipenv가 아냐!!

**Comment by antlikelion** [comment]
지금 다시 pull request확인해보니까 requirements.txt 파일 안의 내용이 다 날아가고 없네요
제 로컬엔 그대로 남아있으니 나중에 모인 자리에서 확인하고 수정해서 merge하면 될 것 같습니다

**Comment by RyanKor** [comment]
![image](https://user-images.githubusercontent.com/40455392/61573920-89f6bd80-aaf1-11e9-92ca-e608f3329654.png)
